require("joanvaro.plugins-setup")
require("joanvaro.core.options")
require("joanvaro.core.keymaps")
require("joanvaro.core.colorscheme")
require("joanvaro.plugins.lualine")
require("joanvaro.plugins.telescope")
require("joanvaro.plugins.nvim-cmp")
require("joanvaro.plugins.lsp.mason")
